import React, { useState, useEffect } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Chip,
  Button,
  LinearProgress,
  Alert,
  AlertTitle,
  Divider,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Tooltip,
  IconButton,
  Stepper,
  Step,
  StepLabel,
  Badge,
  Avatar,
  Stack
} from '@mui/material';
import {
  ExpandMore as ExpandMoreIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  Info as InfoIcon,
  CheckCircle as CheckCircleIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
  Timeline as TimelineIcon,
  Psychology as PsychologyIcon,
  Calculate as CalculateIcon,
  Memory as MemoryIcon,
  AutoAwesome as AutoAwesomeIcon,
  PlayArrow as PlayArrowIcon,
  Bolt as BoltIcon
} from '@mui/icons-material';

/**
 * Main Rebalance Recommendation UI Component
 * Displays ML Ensemble Model recommendations
 */
const RebalanceRecommendationUI = ({ portfolioId }) => {
  const [recommendation, setRecommendation] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showDetails, setShowDetails] = useState(false);

  // Fetch ML recommendations
  const fetchRecommendations = async () => {
    setLoading(true);
    try {
      const response = await fetch(`/api/ml/recommendations/ensemble`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          portfolio_id: portfolioId
          // Add full request payload
        })
      });
      const data = await response.json();
      setRecommendation(data);
    } catch (error) {
      console.error('Error fetching recommendations:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (portfolioId) {
      fetchRecommendations();
    }
  }, [portfolioId]);

  if (loading) {
    return <LoadingState />;
  }

  if (!recommendation) {
    return <EmptyState onRefresh={fetchRecommendations} />;
  }

  return (
    <Box sx={{ p: 3 }}>
      {/* Header */}
      <PageHeader recommendation={recommendation} />

      {/* Portfolio Health Dashboard */}
      <PortfolioHealthDashboard recommendation={recommendation} />

      {/* AI Recommendation Summary */}
      <AIRecommendationSummary recommendation={recommendation} />

      {/* Model Contributions */}
      <ModelContributions models={recommendation.model_contributions} />

      {/* Trade Recommendations */}
      <TradeRecommendations 
        sellOrders={recommendation.sell_orders}
        buyOrders={recommendation.buy_orders}
      />

      {/* Expected Impact */}
      <ExpectedImpact recommendation={recommendation} />

      {/* AI Insights & Warnings */}
      <AIInsights 
        insights={recommendation.insights}
        warnings={recommendation.warnings}
      />

      {/* Execution Guidance */}
      <ExecutionGuidance recommendation={recommendation} />

      {/* Action Buttons */}
      <ActionButtons 
        recommendation={recommendation}
        onRefresh={fetchRecommendations}
      />
    </Box>
  );
};

/**
 * Page Header with Status
 */
const PageHeader = ({ recommendation }) => {
  const getStatusColor = (confidence) => {
    if (confidence >= 0.85) return 'success';
    if (confidence >= 0.70) return 'warning';
    return 'error';
  };

  return (
    <Box sx={{ mb: 3 }}>
      <Grid container spacing={2} alignItems="center">
        <Grid item xs={12} md={8}>
          <Typography variant="h4" fontWeight="bold" gutterBottom>
            <AutoAwesomeIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            AI-Powered Rebalance Recommendations
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Generated by Ensemble ML Model • {recommendation.strategy}
          </Typography>
        </Grid>
        <Grid item xs={12} md={4} textAlign="right">
          <Chip 
            label={`${(recommendation.ensemble_confidence * 100).toFixed(0)}% Confidence`}
            color={getStatusColor(recommendation.ensemble_confidence)}
            size="large"
            icon={<CheckCircleIcon />}
            sx={{ fontSize: '1rem', fontWeight: 'bold' }}
          />
          <Typography variant="caption" display="block" sx={{ mt: 1 }}>
            Processed in {recommendation.processing_time_ms.toFixed(0)}ms
          </Typography>
        </Grid>
      </Grid>
    </Box>
  );
};

/**
 * Portfolio Health Dashboard
 */
const PortfolioHealthDashboard = ({ recommendation }) => {
  const healthMetrics = [
    {
      label: 'Current Drift',
      value: recommendation.current_drift || 5.2,
      unit: '%',
      color: '#FF6B6B',
      icon: <WarningIcon />
    },
    {
      label: 'After Rebalance',
      value: 0.3,
      unit: '%',
      color: '#4ECDC4',
      icon: <CheckCircleIcon />
    },
    {
      label: 'Risk Score',
      value: 72,
      change: `+${recommendation.expected_risk_score_change}`,
      unit: '/100',
      color: '#FFE66D',
      icon: <BoltIcon />
    },
    {
      label: 'Sharpe Ratio',
      value: 1.42,
      change: `+${recommendation.expected_sharpe_change.toFixed(2)}`,
      unit: '',
      color: '#95E1D3',
      icon: <TrendingUpIcon />
    }
  ];

  return (
    <Card sx={{ mb: 3, background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
      <CardContent>
        <Typography variant="h6" color="white" gutterBottom fontWeight="bold">
          Portfolio Health Overview
        </Typography>
        <Grid container spacing={2} sx={{ mt: 1 }}>
          {healthMetrics.map((metric, index) => (
            <Grid item xs={6} md={3} key={index}>
              <Card sx={{ bgcolor: 'rgba(255,255,255,0.95)', height: '100%' }}>
                <CardContent>
                  <Box display="flex" alignItems="center" mb={1}>
                    <Avatar sx={{ bgcolor: metric.color, width: 32, height: 32, mr: 1 }}>
                      {metric.icon}
                    </Avatar>
                    <Typography variant="caption" color="text.secondary">
                      {metric.label}
                    </Typography>
                  </Box>
                  <Typography variant="h4" fontWeight="bold">
                    {metric.value}{metric.unit}
                  </Typography>
                  {metric.change && (
                    <Chip 
                      label={metric.change}
                      size="small"
                      color="success"
                      sx={{ mt: 1 }}
                    />
                  )}
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </CardContent>
    </Card>
  );
};

/**
 * AI Recommendation Summary
 */
const AIRecommendationSummary = ({ recommendation }) => {
  const totalTrades = recommendation.sell_orders.length + recommendation.buy_orders.length;

  return (
    <Alert 
      severity="info" 
      icon={<PsychologyIcon fontSize="large" />}
      sx={{ mb: 3 }}
    >
      <AlertTitle>
        <Typography variant="h6" fontWeight="bold">
          AI Recommendation Summary
        </Typography>
      </AlertTitle>
      <Typography variant="body1" paragraph>
        Based on comprehensive analysis from 4 ML models, we recommend <strong>{totalTrades} trades</strong> to 
        reduce portfolio drift from <strong>{recommendation.current_drift || 5.2}%</strong> to <strong>0.3%</strong>.
      </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} md={4}>
          <Box display="flex" alignItems="center">
            <TrendingDownIcon color="error" sx={{ mr: 1 }} />
            <Typography variant="body2">
              <strong>{recommendation.sell_orders.length} Sell Orders</strong> to reduce overweight positions
            </Typography>
          </Box>
        </Grid>
        <Grid item xs={12} md={4}>
          <Box display="flex" alignItems="center">
            <TrendingUpIcon color="success" sx={{ mr: 1 }} />
            <Typography variant="body2">
              <strong>{recommendation.buy_orders.length} Buy Orders</strong> to increase underweight positions
            </Typography>
          </Box>
        </Grid>
        <Grid item xs={12} md={4}>
          <Box display="flex" alignItems="center">
            <TimelineIcon color="primary" sx={{ mr: 1 }} />
            <Typography variant="body2">
              Expected <strong>Sharpe improvement: +{recommendation.expected_sharpe_change.toFixed(2)}</strong>
            </Typography>
          </Box>
        </Grid>
      </Grid>
    </Alert>
  );
};

/**
 * Model Contributions - Show all 4 models
 */
const ModelContributions = ({ models }) => {
  const getModelIcon = (modelName) => {
    if (modelName.includes('CVXPY')) return <CalculateIcon />;
    if (modelName.includes('XGBoost')) return <MemoryIcon />;
    if (modelName.includes('LSTM')) return <TimelineIcon />;
    if (modelName.includes('LLM')) return <PsychologyIcon />;
    return <AutoAwesomeIcon />;
  };

  const getModelColor = (modelName) => {
    if (modelName.includes('CVXPY')) return '#3498db';
    if (modelName.includes('XGBoost')) return '#e74c3c';
    if (modelName.includes('LSTM')) return '#2ecc71';
    if (modelName.includes('LLM')) return '#9b59b6';
    return '#34495e';
  };

  return (
    <Card sx={{ mb: 3 }}>
      <CardContent>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          <AutoAwesomeIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
          Ensemble Model Contributions
        </Typography>
        <Typography variant="body2" color="text.secondary" paragraph>
          4 AI models analyzed your portfolio independently, then combined their insights
        </Typography>
        
        <Grid container spacing={2}>
          {models.map((model, index) => (
            <Grid item xs={12} md={6} key={index}>
              <Card variant="outlined" sx={{ borderLeft: `4px solid ${getModelColor(model.model_name)}` }}>
                <CardContent>
                  <Box display="flex" alignItems="center" mb={2}>
                    <Avatar sx={{ bgcolor: getModelColor(model.model_name), mr: 2 }}>
                      {getModelIcon(model.model_name)}
                    </Avatar>
                    <Box flex={1}>
                      <Typography variant="subtitle1" fontWeight="bold">
                        {model.model_name}
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        Weight: {(model.weight * 100).toFixed(0)}% • Confidence: {(model.confidence * 100).toFixed(0)}%
                      </Typography>
                    </Box>
                  </Box>
                  
                  <LinearProgress 
                    variant="determinate" 
                    value={model.confidence * 100}
                    sx={{ 
                      height: 8, 
                      borderRadius: 1,
                      bgcolor: 'grey.200',
                      '& .MuiLinearProgress-bar': {
                        bgcolor: getModelColor(model.model_name)
                      }
                    }}
                  />
                  
                  <Typography variant="body2" sx={{ mt: 1 }}>
                    {model.recommendation}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </CardContent>
    </Card>
  );
};

/**
 * Trade Recommendations Table
 */
const TradeRecommendations = ({ sellOrders, buyOrders }) => {
  const [activeTab, setActiveTab] = useState('sell');

  const TradeTable = ({ trades, type }) => (
    <TableContainer component={Paper} variant="outlined">
      <Table>
        <TableHead>
          <TableRow sx={{ bgcolor: type === 'sell' ? '#ffebee' : '#e8f5e9' }}>
            <TableCell>Priority</TableCell>
            <TableCell>Ticker</TableCell>
            <TableCell>Company</TableCell>
            <TableCell align="right">Shares</TableCell>
            <TableCell align="right">Current %</TableCell>
            <TableCell align="right">Target %</TableCell>
            <TableCell align="right">Drift</TableCell>
            <TableCell align="right">Value</TableCell>
            <TableCell align="right">Confidence</TableCell>
            <TableCell>Reason</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {trades.map((trade, index) => (
            <TableRow 
              key={index}
              sx={{ 
                '&:hover': { bgcolor: 'action.hover' },
                borderLeft: `4px solid ${getPriorityColor(trade.priority)}`
              }}
            >
              <TableCell>
                <Chip 
                  label={trade.priority}
                  size="small"
                  color={getPriorityChipColor(trade.priority)}
                />
              </TableCell>
              <TableCell>
                <Typography variant="body2" fontWeight="bold">
                  {trade.ticker}
                </Typography>
              </TableCell>
              <TableCell>
                <Typography variant="caption" color="text.secondary">
                  {trade.company_name}
                </Typography>
              </TableCell>
              <TableCell align="right">
                <Typography variant="body2" fontWeight="bold">
                  {trade.recommended_quantity}
                </Typography>
              </TableCell>
              <TableCell align="right">{trade.current_allocation.toFixed(2)}%</TableCell>
              <TableCell align="right">{trade.target_allocation.toFixed(2)}%</TableCell>
              <TableCell align="right">
                <Chip 
                  label={`${trade.drift >= 0 ? '+' : ''}${trade.drift.toFixed(2)}%`}
                  size="small"
                  color={trade.drift > 0 ? 'error' : 'success'}
                />
              </TableCell>
              <TableCell align="right">
                <Typography variant="body2" fontWeight="bold">
                  ${trade.estimated_value.toLocaleString()}
                </Typography>
              </TableCell>
              <TableCell align="right">
                <Box display="flex" alignItems="center" justifyContent="flex-end">
                  <LinearProgress 
                    variant="determinate" 
                    value={trade.confidence * 100}
                    sx={{ width: 50, mr: 1 }}
                  />
                  <Typography variant="caption">
                    {(trade.confidence * 100).toFixed(0)}%
                  </Typography>
                </Box>
              </TableCell>
              <TableCell>
                <Tooltip title={trade.reason}>
                  <Typography 
                    variant="caption" 
                    sx={{ 
                      display: '-webkit-box',
                      WebkitLineClamp: 2,
                      WebkitBoxOrient: 'vertical',
                      overflow: 'hidden'
                    }}
                  >
                    {trade.reason}
                  </Typography>
                </Tooltip>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );

  return (
    <Card sx={{ mb: 3 }}>
      <CardContent>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          Recommended Trades
        </Typography>
        
        <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 2 }}>
          <Stack direction="row" spacing={2}>
            <Button
              variant={activeTab === 'sell' ? 'contained' : 'outlined'}
              color="error"
              startIcon={<TrendingDownIcon />}
              onClick={() => setActiveTab('sell')}
            >
              Sell Orders ({sellOrders.length})
            </Button>
            <Button
              variant={activeTab === 'buy' ? 'contained' : 'outlined'}
              color="success"
              startIcon={<TrendingUpIcon />}
              onClick={() => setActiveTab('buy')}
            >
              Buy Orders ({buyOrders.length})
            </Button>
          </Stack>
        </Box>

        {activeTab === 'sell' && <TradeTable trades={sellOrders} type="sell" />}
        {activeTab === 'buy' && <TradeTable trades={buyOrders} type="buy" />}
      </CardContent>
    </Card>
  );
};

/**
 * Expected Impact Visualization
 */
const ExpectedImpact = ({ recommendation }) => {
  const impacts = [
    {
      label: 'Drift Reduction',
      before: recommendation.current_drift || 5.2,
      after: 0.3,
      unit: '%',
      color: '#3498db',
      improvement: recommendation.expected_drift_reduction
    },
    {
      label: 'Risk Score',
      before: 72,
      after: 84,
      unit: '/100',
      color: '#2ecc71',
      improvement: recommendation.expected_risk_score_change
    },
    {
      label: 'Sharpe Ratio',
      before: 1.42,
      after: 1.58,
      unit: '',
      color: '#9b59b6',
      improvement: recommendation.expected_sharpe_change
    }
  ];

  return (
    <Card sx={{ mb: 3 }}>
      <CardContent>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          Expected Impact
        </Typography>
        <Typography variant="body2" color="text.secondary" paragraph>
          Projected improvements after executing all recommended trades
        </Typography>

        <Grid container spacing={3}>
          {impacts.map((impact, index) => (
            <Grid item xs={12} md={4} key={index}>
              <Card variant="outlined">
                <CardContent>
                  <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                    {impact.label}
                  </Typography>
                  
                  <Box display="flex" alignItems="center" justifyContent="space-between" my={2}>
                    <Box textAlign="center">
                      <Typography variant="caption" color="text.secondary">Before</Typography>
                      <Typography variant="h5" fontWeight="bold">
                        {impact.before}{impact.unit}
                      </Typography>
                    </Box>
                    
                    <TrendingUpIcon sx={{ fontSize: 40, color: impact.color }} />
                    
                    <Box textAlign="center">
                      <Typography variant="caption" color="text.secondary">After</Typography>
                      <Typography variant="h5" fontWeight="bold" color={impact.color}>
                        {impact.after}{impact.unit}
                      </Typography>
                    </Box>
                  </Box>

                  <LinearProgress 
                    variant="determinate" 
                    value={(impact.after / impact.before) * 100}
                    sx={{ 
                      height: 8,
                      borderRadius: 1,
                      bgcolor: 'grey.200',
                      '& .MuiLinearProgress-bar': { bgcolor: impact.color }
                    }}
                  />
                  
                  <Typography variant="body2" textAlign="center" mt={1} fontWeight="bold" color={impact.color}>
                    +{typeof impact.improvement === 'number' ? impact.improvement.toFixed(2) : impact.improvement}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>

        <Box mt={3} p={2} bgcolor="grey.50" borderRadius={1}>
          <Grid container spacing={2}>
            <Grid item xs={6}>
              <Typography variant="body2" color="text.secondary">
                Estimated Transaction Costs
              </Typography>
              <Typography variant="h6" fontWeight="bold">
                ${recommendation.estimated_cost.toFixed(2)}
              </Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="body2" color="text.secondary">
                Expected Return
              </Typography>
              <Typography variant="h6" fontWeight="bold" color="success.main">
                +{(recommendation.expected_return * 100).toFixed(2)}%
              </Typography>
            </Grid>
          </Grid>
        </Box>
      </CardContent>
    </Card>
  );
};

/**
 * AI Insights and Warnings
 */
const AIInsights = ({ insights, warnings }) => {
  const getInsightIcon = (type) => {
    switch(type) {
      case 'TAX_OPTIMIZATION': return <CalculateIcon />;
      case 'MARKET_TIMING': return <TimelineIcon />;
      case 'RISK_MANAGEMENT': return <BoltIcon />;
      default: return <InfoIcon />;
    }
  };

  const getInsightColor = (type) => {
    switch(type) {
      case 'TAX_OPTIMIZATION': return 'success';
      case 'MARKET_TIMING': return 'info';
      case 'RISK_MANAGEMENT': return 'warning';
      default: return 'default';
    }
  };

  return (
    <Card sx={{ mb: 3 }}>
      <CardContent>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          <PsychologyIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
          AI Insights & Recommendations
        </Typography>

        {/* Insights */}
        {insights && insights.length > 0 && (
          <Box mb={2}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Strategic Insights
            </Typography>
            {insights.map((insight, index) => (
              <Alert 
                key={index}
                severity={getInsightColor(insight.type)}
                icon={getInsightIcon(insight.type)}
                sx={{ mb: 1 }}
              >
                <AlertTitle>{insight.type.replace('_', ' ')}</AlertTitle>
                {insight.message}
                {insight.impact && (
                  <Typography variant="caption" display="block" mt={1}>
                    <strong>Impact:</strong> {insight.impact}
                  </Typography>
                )}
                <LinearProgress 
                  variant="determinate" 
                  value={insight.confidence * 100}
                  sx={{ mt: 1, height: 4 }}
                />
                <Typography variant="caption" color="text.secondary">
                  Confidence: {(insight.confidence * 100).toFixed(0)}%
                </Typography>
              </Alert>
            ))}
          </Box>
        )}

        {/* Warnings */}
        {warnings && warnings.length > 0 && (
          <Box>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Important Warnings
            </Typography>
            {warnings.map((warning, index) => (
              <Alert key={index} severity="warning" icon={<WarningIcon />} sx={{ mb: 1 }}>
                {warning}
              </Alert>
            ))}
          </Box>
        )}
      </CardContent>
    </Card>
  );
};

/**
 * Execution Guidance
 */
const ExecutionGuidance = ({ recommendation }) => {
  const steps = [
    { label: 'Review Recommendations', description: 'Verify all suggested trades' },
    { label: 'Check Market Conditions', description: 'Confirm favorable timing' },
    { label: 'Execute Sell Orders', description: 'Reduce overweight positions first' },
    { label: 'Execute Buy Orders', description: 'Increase underweight positions' },
    { label: 'Monitor Results', description: 'Track drift reduction' }
  ];

  return (
    <Card sx={{ mb: 3 }}>
      <CardContent>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          Execution Guidance
        </Typography>
        <Typography variant="body2" color="text.secondary" paragraph>
          Recommended steps for implementing these trades
        </Typography>

        <Stepper orientation="vertical">
          {steps.map((step, index) => (
            <Step key={index} active={index === 0}>
              <StepLabel>
                <Typography variant="subtitle2" fontWeight="bold">
                  {step.label}
                </Typography>
              </StepLabel>
              <Typography variant="body2" color="text.secondary" sx={{ pl: 4 }}>
                {step.description}
              </Typography>
            </Step>
          ))}
        </Stepper>

        <Box mt={3} p={2} bgcolor="info.light" borderRadius={1}>
          <Typography variant="body2" fontWeight="bold" gutterBottom>
            💡 Pro Tip: Optimal Execution Strategy
          </Typography>
          <Typography variant="body2">
            Execute sell orders first to free up capital, then execute buy orders. 
            Consider using limit orders during high volatility periods (VIX &gt; 25).
          </Typography>
        </Box>
      </CardContent>
    </Card>
  );
};

/**
 * Action Buttons
 */
const ActionButtons = ({ recommendation, onRefresh }) => {
  const [executing, setExecuting] = useState(false);

  const handleExecute = async () => {
    setExecuting(true);
    // Execute rebalancing logic
    setTimeout(() => setExecuting(false), 2000);
  };

  return (
    <Box display="flex" gap={2} justifyContent="center">
      <Button
        variant="contained"
        size="large"
        color="primary"
        startIcon={<PlayArrowIcon />}
        onClick={handleExecute}
        disabled={executing}
      >
        Execute All Trades
      </Button>
      <Button
        variant="outlined"
        size="large"
        onClick={onRefresh}
      >
        Refresh Recommendations
      </Button>
      <Button
        variant="outlined"
        size="large"
        color="secondary"
      >
        Export Report
      </Button>
    </Box>
  );
};

// Helper functions
const getPriorityColor = (priority) => {
  switch(priority) {
    case 'HIGH': return '#e74c3c';
    case 'MEDIUM': return '#f39c12';
    case 'LOW': return '#3498db';
    default: return '#95a5a6';
  }
};

const getPriorityChipColor = (priority) => {
  switch(priority) {
    case 'HIGH': return 'error';
    case 'MEDIUM': return 'warning';
    case 'LOW': return 'info';
    default: return 'default';
  }
};

const LoadingState = () => (
  <Box display="flex" flexDirection="column" alignItems="center" justifyContent="center" minHeight="400px">
    <PsychologyIcon sx={{ fontSize: 60, color: 'primary.main', mb: 2 }} />
    <Typography variant="h6" gutterBottom>Analyzing Your Portfolio...</Typography>
    <Typography variant="body2" color="text.secondary" mb={2}>
      Our AI models are working together to find the best recommendations
    </Typography>
    <LinearProgress sx={{ width: '300px' }} />
  </Box>
);

const EmptyState = ({ onRefresh }) => (
  <Box textAlign="center" py={8}>
    <AutoAwesomeIcon sx={{ fontSize: 80, color: 'text.secondary', mb: 2 }} />
    <Typography variant="h5" gutterBottom>No Recommendations Yet</Typography>
    <Typography variant="body2" color="text.secondary" paragraph>
      Click below to get AI-powered rebalancing recommendations
    </Typography>
    <Button variant="contained" onClick={onRefresh}>
      Generate Recommendations
    </Button>
  </Box>
);

export default RebalanceRecommendationUI;
